#!/usr/bin/env python3
"""Generate crates/bingsu-core/src/ucd.rs from three Unicode 17.0.0 files.

The version must equal unicode_segmentation::UNICODE_VERSION (core test
ucd_version_matches_segmentation). Inputs are verified by sha256 before use;
a mismatch stops the run. Usage:
  gen.py --ucd DIR --out crates/bingsu-core/src/ucd.rs     write the table
  gen.py --ucd DIR --check crates/bingsu-core/src/ucd.rs   exit 1 if it differs
DIR holds EastAsianWidth.txt, DerivedGeneralCategory.txt and emoji-data.txt
(fetch.sh downloads them)."""
import argparse
import hashlib
import pathlib
import sys

VERSION = (17, 0, 0)
SHA256 = {
    "EastAsianWidth.txt": "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
    "DerivedGeneralCategory.txt": "d62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e",
    "emoji-data.txt": "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
}
# Width classes (src/width.rs maps them to cells).
NARROW, WIDE, AMBIGUOUS, ZERO, UNASSIGNED = 0, 1, 2, 3, 4
# Format characters (gc=Cf) that sanitize keeps: ZWJ, which emoji sequences
# need (spec section 3 step 1). Every other Cf is removed.
KEEP_CF = {0x200D}


def load(dirpath, name):
    data = (dirpath / name).read_bytes()
    got = hashlib.sha256(data).hexdigest()
    if got != SHA256[name]:
        sys.exit(f"{name}: sha256 {got}, want {SHA256[name]}")
    return data.decode("utf-8")


def ranges(text):
    """Yield (lo, hi, value) from 'XXXX..YYYY ; value # ...' lines."""
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        cps, value = (s.strip() for s in body.split(";")[:2])
        lo, _, hi = cps.partition("..")
        yield int(lo, 16), int(hi or lo, 16), value


def merged(pairs):
    """Merge adjacent or overlapping (lo, hi, v) with the same v; sorted."""
    out = []
    for lo, hi, v in sorted(pairs):
        if out and out[-1][2] == v and out[-1][1] + 1 >= lo:
            out[-1] = (out[-1][0], max(out[-1][1], hi), v)
        else:
            out.append((lo, hi, v))
    return out


def build(dirpath):
    cls = [UNASSIGNED] * 0x110000
    gc = ["Cn"] * 0x110000
    for lo, hi, v in ranges(load(dirpath, "DerivedGeneralCategory.txt")):
        for cp in range(lo, hi + 1):
            gc[cp] = v
    eaw = ["N"] * 0x110000
    text = load(dirpath, "EastAsianWidth.txt")
    # Defaults for unlisted code points come first ("# @missing" lines, in
    # file order: the whole range N, then the CJK blocks W).
    missing = [line.removeprefix("# @missing:") for line in text.splitlines()
               if line.startswith("# @missing:")]
    if not missing:
        sys.exit("EastAsianWidth.txt: no @missing lines")
    for lo, hi, v in [*ranges("\n".join(missing)), *ranges(text)]:
        for cp in range(lo, hi + 1):
            eaw[cp] = v
    for cp in range(0x110000):
        if gc[cp] in ("Mn", "Me"):
            cls[cp] = ZERO
        elif gc[cp] == "Cn":
            cls[cp] = WIDE if eaw[cp] in ("W", "F") else UNASSIGNED
        elif eaw[cp] in ("W", "F"):
            cls[cp] = WIDE
        elif eaw[cp] == "A":
            cls[cp] = AMBIGUOUS
        else:
            cls[cp] = NARROW
    width = merged((cp, cp, c) for cp, c in enumerate(cls) if c != NARROW)
    emoji = load(dirpath, "emoji-data.txt")
    pres = merged((lo, hi, 0) for lo, hi, v in ranges(emoji) if v == "Emoji_Presentation")
    pict = merged((lo, hi, 0) for lo, hi, v in ranges(emoji) if v == "Extended_Pictographic")
    removed = merged((cp, cp, 0) for cp in range(0x110000)
                     if gc[cp] in ("Cf", "Zl", "Zp") and cp not in KEEP_CF)
    return width, pres, pict, removed


def render(width, pres, pict, removed):
    lines = [
        "// @generated by tools/gen-ucd-tables/gen.py from Unicode 17.0.0. Do not edit.",
        "//! Unicode tables for width (src/width.rs) and sanitize (src/sanitize.rs).",
        "",
        "pub const UNICODE_VERSION: (u64, u64, u64) = (17, 0, 0);",
        "",
        "/// Width class of every code point not listed here is 0 (narrow).",
        "/// 1 wide (W, F), 2 East Asian Ambiguous, 3 combining (Mn, Me),",
        "/// 4 unassigned. Sorted, non-overlapping, inclusive.",
        "pub(crate) const WIDTH_CLASS: &[(u32, u32, u8)] = &[",
    ]
    lines += [f"    (0x{lo:04X}, 0x{hi:04X}, {v})," for lo, hi, v in width]
    lines += ["];", "", "/// Emoji_Presentation=Yes.", "pub(crate) const EMOJI_PRESENTATION: &[(u32, u32)] = &["]
    lines += [f"    (0x{lo:04X}, 0x{hi:04X})," for lo, hi, _ in pres]
    lines += ["];", "", "/// Extended_Pictographic=Yes.", "pub(crate) const EXTENDED_PICTOGRAPHIC: &[(u32, u32)] = &["]
    lines += [f"    (0x{lo:04X}, 0x{hi:04X})," for lo, hi, _ in pict]
    lines += ["];", "", "/// Removed by sanitize: gc Cf except U+200D, Zl, Zp.",
              "pub(crate) const REMOVED_FORMAT: &[(u32, u32)] = &["]
    lines += [f"    (0x{lo:04X}, 0x{hi:04X})," for lo, hi, _ in removed]
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ucd", required=True, type=pathlib.Path)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--out", type=pathlib.Path)
    group.add_argument("--check", type=pathlib.Path)
    a = ap.parse_args()
    text = render(*build(a.ucd))
    if a.out:
        a.out.write_text(text)
        return 0
    if a.check.read_text() != text:
        print(f"{a.check} differs from the generator output; run gen.py --out", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
