[package]
name = "bingsu"
version = "0.0.0"
description = "Cross-shell prompt engine"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bingsu-core = { path = "../bingsu-core" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
